# list FOREX to DOWNLOAD ----
FX_list_expanded<<-list(FX_major=list("EURUSD"="Euro/US Dollar"
                                      ,"GBPUSD"="British Pound/US Dollar"
                                      ,"USDCAD"="US Dollar/Canadian Dollar"
                                      ,"USDCHF"="US Dollar/Swiss Franc"
                                      ,"USDJPY"="US Dollar/Japanese Yen")
                        ,FX_minor=list("AUDCAD"="Australian Dollar/Canadian Dollar"
                                       ,"AUDCHF"="Australian Dollar/Swiss Frank"
                                       ,"AUDJPY"="Australian Dollar/Japanese Yen"
                                       ,"AUDNZD"="Australian Dollar/New Zealand Dollar"
                                       ,"AUDUSD"="Australian Dollar/US Dollar"
                                       ,"CADCHF"="Canadian Dollar /Swiss Franc"
                                       ,"CADJPY"="Canadian Dollar/Japanese Yen"
                                       ,"CHFJPY"="Swiss Franc/Japanese Yen"
                                       ,"EURAUD"="Euro/Australian Dollar"
                                       ,"EURCAD"="Euro/Canadian Dollar"
                                       ,"EURCHF"="Euro/Swiss Franc"
                                       ,"EURGBP"="Euro/British Pound"
                                       ,"EURJPY"="Euro/Japanese Yen"
                                       ,"EURNZD"="Euro/New Zealand Dollar"
                                       ,"GBPAUD"="British Pound/Australian Dollar"
                                       ,"GBPCAD"="British Pound/Canadian Dollar"
                                       ,"GBPCHF"="British Pound/Swiss Franc"
                                       ,"GBPJPY"="British Pound/Japanese Yen"
                                       ,"GBPNZD"="British Pound/New Zealand Dollar"
                                       ,"NZDCAD"="New Zealand Dollar/Canadian Dollar"
                                       ,"NZDCHF"="New Zealand Dollar/Swiss Franc"
                                       ,"NZDJPY"="New Zealand Dollar/Japanese Yen"
                                       ,"NZDUSD"="New Zealand Dollar/US Dollar")
)

FX_list<<-list(#"AUDCAD"="AUDCAD"
               #,"AUDCHF"="AUDCHF"
               #,"AUDJPY"="AUDJPY"
               #,"AUDNZD"="AUDNZD"
               #,"AUDUSD"="AUDUSD"
               #,
               "CADCHF"="CADCHF"
               #,"CADJPY"="CADJPY"
               #,"CHFJPY"="CHFJPY"
               #,"EURAUD"="EURAUD"
               ,"EURCAD"="EURCAD"
               ,"EURCHF"="EURCHF"
               ,"EURGBP"="EURGBP"
               #,"EURJPY"="EURJPY"
               #,"EURNZD"="EURNZD"
               ,"EURUSD"="EURUSD"
               #,"GBPAUD"="GBPAUD"
               ,"GBPCAD"="GBPCAD"
               ,"GBPCHF"="GBPCHF"
               #,"GBPJPY"="GBPJPY"
               #,"GBPNZD"="GBPNZD"
               ,"GBPUSD"="GBPUSD"
               #,"NZDCAD"="NZDCAD"
               #,"NZDCHF"="NZDCHF"
               #,"NZDJPY"="NZDJPY"
               #,"NZDUSD"="NZDUSD"
               ,"USDCAD"="USDCAD"
               ,"USDCHF"="USDCHF"
               #,"USDJPY"="USDJPY"
)
